name: basenji_personalized_exp
channels:
  - defaults
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - astropy
  - biopython
  - cython
  - h5py
  - intervaltree
  - joblib
  - matplotlib
  - natsort
  - networkx
  - numpy
  - packaging
  - pandas
  - pillow
  - pybedtools
  - pybigwig
  - pysam
  - python=3.8
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tabulate
  - tqdm
  - pip:
    - cooler
    - cooltools
